### ISSUE TITLE
[v1.4.4.462] blank icon in SysTray

### ISSUE THREAD

**Issue by Kaligula0** [stefankueng/CryptSync#99] opened 2022-12-31 13:14 UTC
After the update from recent (1.4.3) to newest (1.4.4) version (which includes icon changing according to sync status) there's no visible icon in SysTray. There's a place where it should be visible, also the tooltip and the right-click menu work; but the icon is invisible.

![image](https://user-images.githubusercontent.com/3950811/210137965-1f1b3424-5577-458f-90ca-302b7bc7d790.png)

Happens on 2 computers with Windows 7. Persists after reboot. Should I provide any additional information?

**Comment by Xddass1** [comment] 2023-01-02 16:01
same here, several Windows 10 and 11

**Comment by DeanoV6** [comment] 2023-01-06 23:10
I'm seeing this too.  Windows 10.

**Comment by stefankueng** [comment] 2023-01-07 08:01
Duplicate of #98

**Closed** 2024-07-20 08:45 UTC
Labels: duplicate
