### ISSUE TITLE
Issue: When selecting "run in background" prompts "Do you really want to quit"

### ISSUE THREAD

**Issue by N3bukadne7ar** [stefankueng/CryptSync#37] opened 2020-04-12 17:40 UTC
Issue: When selecting "run in background" prompts "Do you really want to quit" -> This doesn't make sense to me since I am not quitting the program, it runs in the background. Otherwise really nice UI, finally a program that actually communicates correctly what it is going to do when I push that "exit" button. To many tools just pretend to exit and then go hide in the tray...
 keep up the good work!

**Comment by stefankueng** [comment] 2020-04-14 05:54
duplicate of #28

**Closed by stefankueng** 2020-04-14 05:54 UTC
